# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-10 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookyBotApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='flight_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookybotuser',
            name='step_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookybotuser',
            name='trail_flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookybotuser',
            name='v_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookybotuser',
            name='v_destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookybotuser',
            name='v_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
